# docker-compose.yml
version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: talk-box-postgres
    restart: always
    environment:
      POSTGRES_USER: talkBoxUser
      POSTGRES_PASSWORD: talkBoxPass
      POSTGRES_DB: talkBoxDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
